<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php

    #Comentario
    //Comentario
    /*Comentario
    varias lineas */

    echo "<p>Hola</p>";
    echo "<br>";
    echo "<p>Adios</p>";

    echo 2/3;
    echo "<br>";
    echo 12%2;

    echo "<br>";

    $x="2";
    $y="5";

    echo $x==$y;
    echo $x+=$y;
?>

<h1>Title</h1>

<?php
    echo min(150,0,-3,2);
    echo "<br>";
    echo round(2.76);
?>
</body>
</html>